/// file      : _syscall.h
/// author    : Siddharth Mishra (admin@brightprogrammer.in)
/// This is free and unencumbered software released into the public domain.
///
/// Internal direct-syscall plumbing for Linux and Darwin (XNU). Use
/// ONLY from .c files in Source/; this header is not exposed via
/// Include/Misra/, the underscore prefix marks it as private to the
/// implementation.
///
/// Provides misra_sys0..misra_sys6 -- thin inline-asm wrappers that
/// invoke a kernel syscall by number with the platform's argument
/// register conventions. On Linux (System V AMD64 / ARM64) the kernel
/// returns the result in rax / x0; negative values < 4096 indicate
/// -errno. On Darwin (XNU) the equivalent paths are gated behind
/// PLATFORM_DARWIN and use the BSD syscall numbers / ABI documented
/// inline; see the Darwin block below.
///
/// Windows is not handled by this header -- the NT ABI differs
/// fundamentally and callers should route those paths through
/// kernel32 directly behind `#if PLATFORM_WINDOWS`. The
/// `FEATURE_DIRECT_SYSCALL` is set by `Misra/Config.h` (generated by
/// meson from the same platform/arch matrix used here); treat it as
/// the gate for direct-syscall vs libc/wrapper fallback.

#ifndef MISRA__SYSCALL_H
#define MISRA__SYSCALL_H

#include <Misra/Types.h>

#if PLATFORM_LINUX && (ARCHITECTURE_X86_64 || ARCHITECTURE_AARCH64)

static inline long misra_sys0(long nr) {
    long ret;
#    if ARCHITECTURE_X86_64
    __asm__ volatile("syscall"
                     : "=a"(ret)
                     : "0"(nr)
                     : "rcx", "r11", "memory");
#    else
    register long x8 __asm__("x8") = nr;
    register long x0 __asm__("x0");
    __asm__ volatile("svc #0"
                     : "=r"(x0)
                     : "r"(x8)
                     : "memory");
    ret = x0;
#    endif
    return ret;
}

static inline long misra_sys1(long nr, long a) {
    long ret;
#    if ARCHITECTURE_X86_64
    __asm__ volatile("syscall"
                     : "=a"(ret)
                     : "0"(nr), "D"(a)
                     : "rcx", "r11", "memory");
#    else
    register long x8 __asm__("x8") = nr;
    register long x0 __asm__("x0") = a;
    __asm__ volatile("svc #0"
                     : "+r"(x0)
                     : "r"(x8)
                     : "memory");
    ret = x0;
#    endif
    return ret;
}

static inline long misra_sys2(long nr, long a, long b) {
    long ret;
#    if ARCHITECTURE_X86_64
    __asm__ volatile("syscall"
                     : "=a"(ret)
                     : "0"(nr), "D"(a), "S"(b)
                     : "rcx", "r11", "memory");
#    else
    register long x8 __asm__("x8") = nr;
    register long x0 __asm__("x0") = a;
    register long x1 __asm__("x1") = b;
    __asm__ volatile("svc #0"
                     : "+r"(x0)
                     : "r"(x8), "r"(x1)
                     : "memory");
    ret = x0;
#    endif
    return ret;
}

static inline long misra_sys3(long nr, long a, long b, long c) {
    long ret;
#    if ARCHITECTURE_X86_64
    __asm__ volatile("syscall"
                     : "=a"(ret)
                     : "0"(nr), "D"(a), "S"(b), "d"(c)
                     : "rcx", "r11", "memory");
#    else
    register long x8 __asm__("x8") = nr;
    register long x0 __asm__("x0") = a;
    register long x1 __asm__("x1") = b;
    register long x2 __asm__("x2") = c;
    __asm__ volatile("svc #0"
                     : "+r"(x0)
                     : "r"(x8), "r"(x1), "r"(x2)
                     : "memory");
    ret = x0;
#    endif
    return ret;
}

static inline long misra_sys4(long nr, long a, long b, long c, long d) {
    long ret;
#    if ARCHITECTURE_X86_64
    register long r10 __asm__("r10") = d;
    __asm__ volatile("syscall"
                     : "=a"(ret)
                     : "0"(nr), "D"(a), "S"(b), "d"(c), "r"(r10)
                     : "rcx", "r11", "memory");
#    else
    register long x8 __asm__("x8") = nr;
    register long x0 __asm__("x0") = a;
    register long x1 __asm__("x1") = b;
    register long x2 __asm__("x2") = c;
    register long x3 __asm__("x3") = d;
    __asm__ volatile("svc #0"
                     : "+r"(x0)
                     : "r"(x8), "r"(x1), "r"(x2), "r"(x3)
                     : "memory");
    ret = x0;
#    endif
    return ret;
}

static inline long misra_sys5(long nr, long a, long b, long c, long d, long e) {
    long ret;
#    if ARCHITECTURE_X86_64
    register long r10 __asm__("r10") = d;
    register long r8 __asm__("r8")   = e;
    __asm__ volatile("syscall"
                     : "=a"(ret)
                     : "0"(nr), "D"(a), "S"(b), "d"(c), "r"(r10), "r"(r8)
                     : "rcx", "r11", "memory");
#    else
    register long x8 __asm__("x8") = nr;
    register long x0 __asm__("x0") = a;
    register long x1 __asm__("x1") = b;
    register long x2 __asm__("x2") = c;
    register long x3 __asm__("x3") = d;
    register long x4 __asm__("x4") = e;
    __asm__ volatile("svc #0"
                     : "+r"(x0)
                     : "r"(x8), "r"(x1), "r"(x2), "r"(x3), "r"(x4)
                     : "memory");
    ret = x0;
#    endif
    return ret;
}

static inline long misra_sys6(long nr, long a, long b, long c, long d, long e, long f) {
    long ret;
#    if ARCHITECTURE_X86_64
    register long r10 __asm__("r10") = d;
    register long r8 __asm__("r8")   = e;
    register long r9 __asm__("r9")   = f;
    __asm__ volatile("syscall"
                     : "=a"(ret)
                     : "0"(nr), "D"(a), "S"(b), "d"(c), "r"(r10), "r"(r8), "r"(r9)
                     : "rcx", "r11", "memory");
#    else
    register long x8 __asm__("x8") = nr;
    register long x0 __asm__("x0") = a;
    register long x1 __asm__("x1") = b;
    register long x2 __asm__("x2") = c;
    register long x3 __asm__("x3") = d;
    register long x4 __asm__("x4") = e;
    register long x5 __asm__("x5") = f;
    __asm__ volatile("svc #0"
                     : "+r"(x0)
                     : "r"(x8), "r"(x1), "r"(x2), "r"(x3), "r"(x4), "r"(x5)
                     : "memory");
    ret = x0;
#    endif
    return ret;
}

// Linux syscall numbers we use (per arch). The standard reference
// is asm/unistd_64.h (x86_64) and asm-generic/unistd.h (aarch64).
#    if ARCHITECTURE_X86_64
#        define MISRA_SYS_read          0
#        define MISRA_SYS_write         1
#        define MISRA_SYS_open          2
#        define MISRA_SYS_close         3
#        define MISRA_SYS_stat          4
#        define MISRA_SYS_fstat         5
#        define MISRA_SYS_lstat         6
#        define MISRA_SYS_poll          7
#        define MISRA_SYS_lseek         8
#        define MISRA_SYS_mmap          9
#        define MISRA_SYS_mprotect      10
#        define MISRA_SYS_munmap        11
#        define MISRA_SYS_ioctl         16
#        define MISRA_SYS_pipe          22
#        define MISRA_SYS_dup2          33
#        define MISRA_SYS_nanosleep     35
#        define MISRA_SYS_getpid        39
#        define MISRA_SYS_gettid        186
#        define MISRA_SYS_rt_sigaction  13
#        define MISRA_SYS_rt_sigreturn  15
#        define MISRA_SYS_unlink        87
#        define MISRA_SYS_rmdir         84
#        define MISRA_SYS_mkdir         83
#        define MISRA_SYS_mkdirat       258
#        define MISRA_SYS_socket        41
#        define MISRA_SYS_connect       42
#        define MISRA_SYS_accept        43
#        define MISRA_SYS_sendto        44
#        define MISRA_SYS_recvfrom      45
#        define MISRA_SYS_bind          49
#        define MISRA_SYS_listen        50
#        define MISRA_SYS_getsockname   51
#        define MISRA_SYS_setsockopt    54
#        define MISRA_SYS_clone         56
#        define MISRA_SYS_fork          57
#        define MISRA_SYS_execve        59
#        define MISRA_SYS_exit          60
#        define MISRA_SYS_exit_group    231
#        define MISRA_SYS_wait4         61
#        define MISRA_SYS_kill          62
#        define MISRA_SYS_fcntl         72
#        define MISRA_SYS_getdents      78
#        define MISRA_SYS_readlink      89
#        define MISRA_SYS_futex         202
#        define MISRA_SYS_clock_gettime 228
#        define MISRA_SYS_openat        257
#        define MISRA_SYS_newfstatat    262
#        define MISRA_SYS_getdents64    217
#        define MISRA_SYS_getrandom     318
#    else // ARCHITECTURE_AARCH64
// aarch64 only has the "modern" syscall set: no SYS_open (use openat),
// no SYS_stat (use newfstatat), no SYS_pipe (use pipe2), no SYS_fork
// (use clone), no SYS_dup2 (use dup3), no SYS_getdents (use getdents64).
#        define MISRA_SYS_read          63
#        define MISRA_SYS_write         64
#        define MISRA_SYS_close         57
#        define MISRA_SYS_fstat         80
#        define MISRA_SYS_lseek         62
#        define MISRA_SYS_mmap          222
#        define MISRA_SYS_mprotect      226
#        define MISRA_SYS_munmap        215
#        define MISRA_SYS_ioctl         29
#        define MISRA_SYS_pipe2         59
#        define MISRA_SYS_dup3          24
#        define MISRA_SYS_nanosleep     101
#        define MISRA_SYS_getpid        172
#        define MISRA_SYS_gettid        178
#        define MISRA_SYS_rt_sigaction  134
#        define MISRA_SYS_rt_sigreturn  139
#        define MISRA_SYS_unlinkat      35 // aarch64: no SYS_unlink/SYS_rmdir, use unlinkat
#        define MISRA_SYS_mkdirat       34 // aarch64: no SYS_mkdir, use mkdirat
#        define MISRA_SYS_socket        198
#        define MISRA_SYS_connect       203
#        define MISRA_SYS_accept        202
#        define MISRA_SYS_sendto        206
#        define MISRA_SYS_recvfrom      207
#        define MISRA_SYS_bind          200
#        define MISRA_SYS_listen        201
#        define MISRA_SYS_getsockname   204
#        define MISRA_SYS_setsockopt    208
#        define MISRA_SYS_clone         220
#        define MISRA_SYS_execve        221
#        define MISRA_SYS_exit          93
#        define MISRA_SYS_exit_group    94
#        define MISRA_SYS_wait4         260
#        define MISRA_SYS_kill          129
#        define MISRA_SYS_fcntl         25
#        define MISRA_SYS_readlink      78 // actually readlinkat on aarch64
#        define MISRA_SYS_readlinkat    78
#        define MISRA_SYS_futex         98
#        define MISRA_SYS_clock_gettime 113
#        define MISRA_SYS_openat        56
#        define MISRA_SYS_newfstatat    79
#        define MISRA_SYS_getdents64    61
#        define MISRA_SYS_ppoll         73
#        define MISRA_SYS_getrandom     278
#    endif

#elif PLATFORM_DARWIN && (ARCHITECTURE_X86_64 || ARCHITECTURE_AARCH64)

// Darwin direct-syscall path. Apple "deprecates" raw syscalls -- the
// stable Apple-supported ABI is libSystem.dylib -- but they still
// function for the BSD-class syscall numbers we use, and Cosmopolitan
// libc (jart/cosmopolitan) is the prior-art reference. Caveat: Apple
// has renumbered BSD syscalls historically (most notoriously in 2008
// and again across some 10.x release transitions). Pin to a tested
// macOS major version and re-verify on each Apple OS bump.
//
// Differences from Linux that show up in this header:
//   - Syscall instruction unchanged on x86_64 (`syscall`), but on
//     aarch64 Darwin uses `svc #0x80` instead of `svc #0`.
//   - Number register on aarch64 is `x16` (not `x8`).
//   - x86_64 numbers carry a `class` prefix; BSD class is `0x2000000`,
//     so `read` is encoded as `0x2000003`. aarch64 numbers are raw.
//   - Error reporting is via the carry flag, not -errno in the
//     return register. We emit `jnc 1f; neg %rax; 1:` (x86_64) or
//     `b.cc 1f; neg x0, x0; 1:` (aarch64) right after the syscall
//     so the caller-visible convention matches Linux: negative
//     return means -errno, non-negative means success.

#    if ARCHITECTURE_X86_64
#        define MISRA_DARWIN_SC(n) ((long)((n) | 0x2000000L)) // BSD class
#    else
#        define MISRA_DARWIN_SC(n) ((long)(n))
#    endif

static inline long misra_sys0(long nr) {
    long ret;
#    if ARCHITECTURE_X86_64
    __asm__ volatile(
        "syscall\n\t"
        "jnc 1f\n\t"
        "negq %%rax\n"
        "1:"
        : "=a"(ret)
        : "0"(nr)
        : "rcx", "r11", "cc", "memory"
    );
#    else
    register long x16_ __asm__("x16") = nr;
    register long x0_ __asm__("x0");
    __asm__ volatile(
        "svc #0x80\n\t"
        "b.cc 1f\n\t"
        "neg x0, x0\n"
        "1:"
        : "=r"(x0_)
        : "r"(x16_)
        : "cc", "memory"
    );
    ret = x0_;
#    endif
    return ret;
}

static inline long misra_sys1(long nr, long a) {
    long ret;
#    if ARCHITECTURE_X86_64
    __asm__ volatile(
        "syscall\n\t"
        "jnc 1f\n\t"
        "negq %%rax\n"
        "1:"
        : "=a"(ret)
        : "0"(nr), "D"(a)
        : "rcx", "r11", "cc", "memory"
    );
#    else
    register long x16_ __asm__("x16") = nr;
    register long x0_ __asm__("x0")   = a;
    __asm__ volatile(
        "svc #0x80\n\t"
        "b.cc 1f\n\t"
        "neg x0, x0\n"
        "1:"
        : "+r"(x0_)
        : "r"(x16_)
        : "cc", "memory"
    );
    ret = x0_;
#    endif
    return ret;
}

static inline long misra_sys2(long nr, long a, long b) {
    long ret;
#    if ARCHITECTURE_X86_64
    __asm__ volatile(
        "syscall\n\t"
        "jnc 1f\n\t"
        "negq %%rax\n"
        "1:"
        : "=a"(ret)
        : "0"(nr), "D"(a), "S"(b)
        : "rcx", "r11", "cc", "memory"
    );
#    else
    register long x16_ __asm__("x16") = nr;
    register long x0_ __asm__("x0")   = a;
    register long x1_ __asm__("x1")   = b;
    __asm__ volatile(
        "svc #0x80\n\t"
        "b.cc 1f\n\t"
        "neg x0, x0\n"
        "1:"
        : "+r"(x0_)
        : "r"(x16_), "r"(x1_)
        : "cc", "memory"
    );
    ret = x0_;
#    endif
    return ret;
}

static inline long misra_sys3(long nr, long a, long b, long c) {
    long ret;
#    if ARCHITECTURE_X86_64
    __asm__ volatile(
        "syscall\n\t"
        "jnc 1f\n\t"
        "negq %%rax\n"
        "1:"
        : "=a"(ret)
        : "0"(nr), "D"(a), "S"(b), "d"(c)
        : "rcx", "r11", "cc", "memory"
    );
#    else
    register long x16_ __asm__("x16") = nr;
    register long x0_ __asm__("x0")   = a;
    register long x1_ __asm__("x1")   = b;
    register long x2_ __asm__("x2")   = c;
    __asm__ volatile(
        "svc #0x80\n\t"
        "b.cc 1f\n\t"
        "neg x0, x0\n"
        "1:"
        : "+r"(x0_)
        : "r"(x16_), "r"(x1_), "r"(x2_)
        : "cc", "memory"
    );
    ret = x0_;
#    endif
    return ret;
}

static inline long misra_sys4(long nr, long a, long b, long c, long d) {
    long ret;
#    if ARCHITECTURE_X86_64
    register long r10 __asm__("r10") = d;
    __asm__ volatile(
        "syscall\n\t"
        "jnc 1f\n\t"
        "negq %%rax\n"
        "1:"
        : "=a"(ret)
        : "0"(nr), "D"(a), "S"(b), "d"(c), "r"(r10)
        : "rcx", "r11", "cc", "memory"
    );
#    else
    register long x16_ __asm__("x16") = nr;
    register long x0_ __asm__("x0")   = a;
    register long x1_ __asm__("x1")   = b;
    register long x2_ __asm__("x2")   = c;
    register long x3_ __asm__("x3")   = d;
    __asm__ volatile(
        "svc #0x80\n\t"
        "b.cc 1f\n\t"
        "neg x0, x0\n"
        "1:"
        : "+r"(x0_)
        : "r"(x16_), "r"(x1_), "r"(x2_), "r"(x3_)
        : "cc", "memory"
    );
    ret = x0_;
#    endif
    return ret;
}

static inline long misra_sys5(long nr, long a, long b, long c, long d, long e) {
    long ret;
#    if ARCHITECTURE_X86_64
    register long r10 __asm__("r10") = d;
    register long r8 __asm__("r8")   = e;
    __asm__ volatile(
        "syscall\n\t"
        "jnc 1f\n\t"
        "negq %%rax\n"
        "1:"
        : "=a"(ret)
        : "0"(nr), "D"(a), "S"(b), "d"(c), "r"(r10), "r"(r8)
        : "rcx", "r11", "cc", "memory"
    );
#    else
    register long x16_ __asm__("x16") = nr;
    register long x0_ __asm__("x0")   = a;
    register long x1_ __asm__("x1")   = b;
    register long x2_ __asm__("x2")   = c;
    register long x3_ __asm__("x3")   = d;
    register long x4_ __asm__("x4")   = e;
    __asm__ volatile(
        "svc #0x80\n\t"
        "b.cc 1f\n\t"
        "neg x0, x0\n"
        "1:"
        : "+r"(x0_)
        : "r"(x16_), "r"(x1_), "r"(x2_), "r"(x3_), "r"(x4_)
        : "cc", "memory"
    );
    ret = x0_;
#    endif
    return ret;
}

static inline long misra_sys6(long nr, long a, long b, long c, long d, long e, long f) {
    long ret;
#    if ARCHITECTURE_X86_64
    register long r10 __asm__("r10") = d;
    register long r8 __asm__("r8")   = e;
    register long r9 __asm__("r9")   = f;
    __asm__ volatile(
        "syscall\n\t"
        "jnc 1f\n\t"
        "negq %%rax\n"
        "1:"
        : "=a"(ret)
        : "0"(nr), "D"(a), "S"(b), "d"(c), "r"(r10), "r"(r8), "r"(r9)
        : "rcx", "r11", "cc", "memory"
    );
#    else
    register long x16_ __asm__("x16") = nr;
    register long x0_ __asm__("x0")   = a;
    register long x1_ __asm__("x1")   = b;
    register long x2_ __asm__("x2")   = c;
    register long x3_ __asm__("x3")   = d;
    register long x4_ __asm__("x4")   = e;
    register long x5_ __asm__("x5")   = f;
    __asm__ volatile(
        "svc #0x80\n\t"
        "b.cc 1f\n\t"
        "neg x0, x0\n"
        "1:"
        : "+r"(x0_)
        : "r"(x16_), "r"(x1_), "r"(x2_), "r"(x3_), "r"(x4_), "r"(x5_)
        : "cc", "memory"
    );
    ret = x0_;
#    endif
    return ret;
}

// XNU BSD syscall numbers. Source: apple-oss-distributions/xnu
// bsd/kern/syscalls.master. Numbers are the same on x86_64 and
// aarch64; only the class-prefix encoding differs (handled by
// MISRA_DARWIN_SC).
#    define MISRA_SYS_exit            MISRA_DARWIN_SC(1)
#    define MISRA_SYS_fork            MISRA_DARWIN_SC(2)
#    define MISRA_SYS_read            MISRA_DARWIN_SC(3)
#    define MISRA_SYS_write           MISRA_DARWIN_SC(4)
#    define MISRA_SYS_open            MISRA_DARWIN_SC(5)
#    define MISRA_SYS_close           MISRA_DARWIN_SC(6)
#    define MISRA_SYS_wait4           MISRA_DARWIN_SC(7)
#    define MISRA_SYS_unlink          MISRA_DARWIN_SC(10)
#    define MISRA_SYS_getpid          MISRA_DARWIN_SC(20)
#    define MISRA_SYS_recvfrom        MISRA_DARWIN_SC(29)
#    define MISRA_SYS_accept          MISRA_DARWIN_SC(30)
#    define MISRA_SYS_getsockname     MISRA_DARWIN_SC(32)
#    define MISRA_SYS_kill            MISRA_DARWIN_SC(37)
#    define MISRA_SYS_pipe            MISRA_DARWIN_SC(42)
#    define MISRA_SYS_rt_sigaction    MISRA_DARWIN_SC(46) // XNU `sigaction`
#    define MISRA_SYS_ioctl           MISRA_DARWIN_SC(54)
#    define MISRA_SYS_execve          MISRA_DARWIN_SC(59)
#    define MISRA_SYS_munmap          MISRA_DARWIN_SC(73)
#    define MISRA_SYS_mprotect        MISRA_DARWIN_SC(74)
#    define MISRA_SYS_dup2            MISRA_DARWIN_SC(90)
#    define MISRA_SYS_fcntl           MISRA_DARWIN_SC(92)
#    define MISRA_SYS_socket          MISRA_DARWIN_SC(97)
#    define MISRA_SYS_connect         MISRA_DARWIN_SC(98)
#    define MISRA_SYS_bind            MISRA_DARWIN_SC(104)
#    define MISRA_SYS_setsockopt      MISRA_DARWIN_SC(105)
#    define MISRA_SYS_listen          MISRA_DARWIN_SC(106)
#    define MISRA_SYS_sendto          MISRA_DARWIN_SC(133)
#    define MISRA_SYS_rmdir           MISRA_DARWIN_SC(137)
#    define MISRA_SYS_rt_sigreturn    MISRA_DARWIN_SC(184) // XNU `sigreturn`
#    define MISRA_SYS_mmap            MISRA_DARWIN_SC(197)
#    define MISRA_SYS_lseek           MISRA_DARWIN_SC(199)
#    define MISRA_SYS_poll            MISRA_DARWIN_SC(230)
#    define MISRA_SYS_stat64          MISRA_DARWIN_SC(338)
#    define MISRA_SYS_fstat64         MISRA_DARWIN_SC(339)
#    define MISRA_SYS_getdirentries64 MISRA_DARWIN_SC(344)
#    define MISRA_SYS_thread_selfid   MISRA_DARWIN_SC(372) // = Linux gettid
#    define MISRA_SYS_openat          MISRA_DARWIN_SC(463)
#    define MISRA_SYS_fstatat64       MISRA_DARWIN_SC(470)
#    define MISRA_SYS_unlinkat        MISRA_DARWIN_SC(472)
#    define MISRA_SYS_mkdir           MISRA_DARWIN_SC(136)
#    define MISRA_SYS_mkdirat         MISRA_DARWIN_SC(475)
// Darwin has no `getrandom`; BSD-class #500 `getentropy` is the
// kernel-CSPRNG entry. 256-byte per-call cap, no flags arg.
#    define MISRA_SYS_getentropy      MISRA_DARWIN_SC(500)
#    define MISRA_SYS_nanosleep       MISRA_DARWIN_SC(240)
#    define MISRA_SYS_readlink        MISRA_DARWIN_SC(58)
#    define MISRA_SYS_readlinkat      MISRA_DARWIN_SC(473)
#    define MISRA_SYS_gettimeofday    MISRA_DARWIN_SC(116)
// Darwin __ulock syscalls (XNU's analogue of Linux's futex). #515 is
// the wait side, #516 the wake side -- both 4-arg / 3-arg shape with
// op-bitfield as first arg. Use UL_COMPARE_AND_WAIT (=1) for 32-bit
// futex-like compare-and-wait semantics, ULF_NO_ERRNO (=0x1000000)
// in the op to get -errno return instead of libSystem errno-set.
#    define MISRA_SYS___ulock_wait    MISRA_DARWIN_SC(515)
#    define MISRA_SYS___ulock_wake    MISRA_DARWIN_SC(516)
// Aliases so files written for the Linux name still compile on Darwin.
#    define MISRA_SYS_exit_group      MISRA_SYS_exit // Darwin has no exit_group; plain exit terminates the whole task
#    define MISRA_SYS_gettid          MISRA_SYS_thread_selfid
#    define MISRA_SYS_fstat           MISRA_SYS_fstat64
#    define MISRA_SYS_stat            MISRA_SYS_stat64
#    define MISRA_SYS_newfstatat      MISRA_SYS_fstatat64
#    define MISRA_SYS_getdents64      MISRA_SYS_getdirentries64

// Darwin's `pipe` syscall ignores the int[2] argument and returns
// the two fds in registers (rax = read fd, rdx = write fd on x86_64;
// x0 = read fd, x1 = write fd on aarch64). Wrap so callers can use
// the Linux-style fds[] buffer convention.
static inline long misra_darwin_pipe(int fds[2]) {
#    if ARCHITECTURE_X86_64
    long fd0, fd1;
    __asm__ volatile(
        "syscall\n\t"
        "jnc 1f\n\t"
        "negq %%rax\n"
        "1:"
        : "=a"(fd0), "=d"(fd1)
        : "0"((long)MISRA_SYS_pipe)
        : "rcx", "r11", "cc", "memory"
    );
    if (fd0 < 0)
        return fd0;
    fds[0] = (int)fd0;
    fds[1] = (int)fd1;
    return 0;
#    else
    register long x16_ __asm__("x16") = (long)MISRA_SYS_pipe;
    register long x0_ __asm__("x0");
    register long x1_ __asm__("x1");
    __asm__ volatile(
        "svc #0x80\n\t"
        "b.cc 1f\n\t"
        "neg x0, x0\n"
        "1:"
        : "=r"(x0_), "=r"(x1_)
        : "r"(x16_)
        : "cc", "memory"
    );
    if (x0_ < 0)
        return x0_;
    fds[0] = (int)x0_;
    fds[1] = (int)x1_;
    return 0;
#    endif
}

#endif // PLATFORM_LINUX && (ARCHITECTURE_X86_64 || ARCHITECTURE_AARCH64)

#endif // MISRA__SYSCALL_H
