############# English navigation ##############

[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Docs"
pageRef = "/blog"
weight = 2

[[main]]
name = "Guides"
pageRef = "/guides"
weight = 3

[[main]]
name = "About"
pageRef = "/about"
weight = 4

[[main]]
name = "Search"
weight = 5

[main.params]
type = "search"

[[main]]
name = "GitHub"
url = "https://github.com/brightprogrammer/MisraStdC"
weight = 6

[main.params]
icon = "github"
