/// file      : std/io.h
/// author    : Siddharth Mishra (admin@brightprogrammer.in)
/// This is free and unencumbered software released into the public domain.
///
/// formatted reading/writing and other magical stuff

// Required for fileno
// Reference : https://forums.freebsd.org/threads/strerror_r-best-practices-posix-vs-gnu.92296/
#define _POSIX_C_SOURCE 200112L

#include <Misra/Std/Io.h>
#include <Misra/Std/Log.h>
#include <Misra/Sys.h>

// TODO(brightprogrammer): refactor this lateron, this is generated by ai and contains redundancy
// but works for now atleast

// stdc
#include <ctype.h>
#include <math.h>

// Helper function to parse format specifiers
static bool ParseFormatSpec(const char* spec, size len, FmtInfo* fi) {
    if (!spec || !fi) {
        LOG_FATAL("Invalid arguments to ParseFormatSpec");
        return false;
    }
    // Empty format specifier is allowed, but spec pointer must not be NULL

    // Initialize format info with defaults
    *fi = (FmtInfo
    ) {.align         = ALIGN_RIGHT,
       .width         = 0,
       .precision     = 6,
       .has_precision = false,
       .is_hex        = false,
       .is_binary     = false,
       .is_octal      = false,
       .is_debug      = false,
       .is_scientific = false,
       .is_caps       = false};

    size pos = 0;

    // Skip initial colon if present
    if (pos < len && spec[pos] == ':') {
        pos++;
        // After colon, we must have some format specifier
        if (pos >= len) {
            LOG_ERROR("Empty format specifier after colon");
            return false;
        }
    }

    // Parse alignment
    if (pos < len) {
        switch (spec[pos]) {
            case '<' :
                fi->align = ALIGN_LEFT;
                pos++;
                break;
            case '>' :
                fi->align = ALIGN_RIGHT;
                pos++;
                break;
            case '^' :
                fi->align = ALIGN_CENTER;
                pos++;
                break;
            default :
                break;
        }
    }

    // Parse width
    if (pos < len && spec[pos] >= '0' && spec[pos] <= '9') {
        size width = 0;
        while (pos < len && spec[pos] >= '0' && spec[pos] <= '9') {
            width = width * 10 + (spec[pos] - '0');
            pos++;
        }
        if (width > 0) {
            fi->width = width;
        }
    }

    // Parse format type first (before precision)
    bool found_type = false;
    size type_pos   = pos;
    while (type_pos < len) {
        if (spec[type_pos] == '.')
            break; // Stop at precision
        switch (spec[type_pos]) {
            case 'x' :
                fi->is_hex = true;
                found_type = true;
                break;
            case 'X' :
                fi->is_hex  = true;
                fi->is_caps = true;
                found_type  = true;
                break;
            case 'b' :
                fi->is_binary = true;
                found_type    = true;
                break;
            case 'o' :
                fi->is_octal = true;
                found_type   = true;
                break;
            case 'e' :
                fi->is_scientific = true;
                found_type        = true;
                break;
            case 'E' :
                fi->is_scientific = true;
                fi->is_caps       = true;
                found_type        = true;
                break;
            case '?' :
                fi->is_debug = true;
                found_type   = true;
                break;
            default :
                break;
        }
        if (found_type) {
            pos = type_pos + 1;
            break;
        }
        type_pos++;
    }

    // Parse precision
    if (pos < len && spec[pos] == '.') {
        pos++;
        if (pos >= len || spec[pos] < '0' || spec[pos] > '9') {
            return false; // Precision must be followed by digits
        }
        size precision = 0;
        while (pos < len && spec[pos] >= '0' && spec[pos] <= '9') {
            precision = precision * 10 + (spec[pos] - '0');
            pos++;
        }
        fi->has_precision = true;
        fi->precision     = precision;
    }

    // Parse any remaining format type after precision
    if (!found_type) {
        while (pos < len) {
            switch (spec[pos]) {
                case 'x' :
                    fi->is_hex = true;
                    break;
                case 'X' :
                    fi->is_hex  = true;
                    fi->is_caps = true;
                    break;
                case 'b' :
                    fi->is_binary = true;
                    break;
                case 'o' :
                    fi->is_octal = true;
                    break;
                case 'e' :
                    fi->is_scientific = true;
                    break;
                case 'E' :
                    fi->is_scientific = true;
                    fi->is_caps       = true;
                    break;
                case '?' :
                    fi->is_debug = true;
                    break;
                default :
                    return false; // Invalid format type
            }
            pos++;
        }
    }

    return true;
}

// Helper function to pad string with spaces
static void PadString(Str* o, size width, Alignment align, size content_len) {
    if (content_len >= width)
        return;

    size pad_len = width - content_len;

    if (align == ALIGN_RIGHT) {
        // Pad on left
        for (size i = 0; i < pad_len; i++) {
            StrPushFront(o, ' ');
        }
    } else if (align == ALIGN_LEFT) {
        // Pad on right
        for (size i = 0; i < pad_len; i++) {
            StrPushBack(o, ' ');
        }
    } else { // ALIGN_CENTER
        size left_pad  = pad_len / 2;
        size right_pad = pad_len - left_pad;

        // Pad on left
        for (size i = 0; i < left_pad; i++) {
            StrPushFront(o, ' ');
        }

        // Pad on right
        for (size i = 0; i < right_pad; i++) {
            StrPushBack(o, ' ');
        }
    }
}

bool StrWriteFmtInternal(Str* o, const char* fmt, TypeSpecificIO* args, size argc) {
    if (!o || !fmt) {
        LOG_FATAL("Invalid arguments");
        return false;
    }

    size arg_idx = 0;
    size fmt_len = 0;
    while (fmt[fmt_len])
        fmt_len++;

    for (size i = 0; i < fmt_len; i++) {
        if (fmt[i] == '{') {
            // Check for escaped brace
            if (i + 1 < fmt_len && fmt[i + 1] == '{') {
                StrPushBack(o, '{');
                i++; // Skip next brace
                continue;
            }

            // Find closing brace
            size brace_start = i;
            size brace_end   = i + 1;
            while (brace_end < fmt_len && fmt[brace_end] != '}') {
                brace_end++;
            }

            // Error if no closing brace found
            if (brace_end >= fmt_len) {
                LOG_ERROR("Unclosed format specifier");
                return false;
            }

            // Extract format specifier
            size spec_len = brace_end - brace_start - 1;

            // Parse format specifier
            FmtInfo fmt_info;
            if (spec_len == 0) {
                // Empty format specifier {} is allowed, initialize with defaults
                fmt_info = (FmtInfo
                ) {.align         = ALIGN_RIGHT,
                   .width         = 0,
                   .precision     = 6,
                   .has_precision = false,
                   .is_hex        = false,
                   .is_binary     = false,
                   .is_octal      = false,
                   .is_debug      = false,
                   .is_scientific = false,
                   .is_caps       = false};
            } else if (!ParseFormatSpec(fmt + brace_start + 1, spec_len, &fmt_info)) {
                LOG_ERROR("Invalid format specifier");
                return false;
            }

            // Check if we have enough arguments
            if (arg_idx >= argc) {
                LOG_ERROR("Not enough arguments for format string");
                return false;
            }

            // Get current argument
            TypeSpecificIO* arg = &args[arg_idx++];
            if (!arg->writer || !arg->data) {
                LOG_ERROR("Invalid argument");
                return false;
            }

            // Write the formatted value
            arg->writer(o, &fmt_info, arg->data);

            // Skip to end of format specifier
            i = brace_end;
        } else if (fmt[i] == '}') {
            // Check for escaped brace
            if (i + 1 < fmt_len && fmt[i + 1] == '}') {
                StrPushBack(o, '}');
                i++; // Skip next brace
                continue;
            }
            LOG_ERROR("Unmatched closing brace");
            return false;
        } else {
            StrPushBack(o, fmt[i]);
        }
    }

    // Check if we used all arguments
    if (arg_idx < argc) {
        LOG_ERROR("Too many arguments for format string");
        return false;
    }

    return true;
}

const char* StrReadFmtInternal(const char* input, const char* fmtstr, TypeSpecificIO* argv, size argc) {
    if (!input || !fmtstr) {
        LOG_FATAL("Invalid arguments");
    }

    const char* p         = fmtstr;
    const char* in        = input;
    size        remaining = ZstrLen(fmtstr);
    size        arg_index = 0; // Current argument index

    while (remaining > 0) {
        if (remaining >= 2 && p[0] == '{' && p[1] == '{') {
            if (!in || *in != '{') {
                LOG_ERROR("Expected '{' in input");
                return NULL;
            }
            in++;
            p         += 2;
            remaining -= 2;
        } else if (remaining >= 2 && p[0] == '}' && p[1] == '}') {
            if (!in || *in != '}') {
                LOG_ERROR("Expected '}' in input");
                return NULL;
            }
            in++;
            p         += 2;
            remaining -= 2;
        } else if (p[0] == '{') {
            p++;
            remaining--;

            // Find closing brace
            const char* start    = p;
            size        spec_len = 0;
            while (remaining > 0 && *p != '}') {
                p++;
                remaining--;
                spec_len++;
            }

            if (remaining == 0 || *p != '}') {
                LOG_ERROR("Unmatched '{' in format string");
                return NULL;
            }

            // Parse optional specifier
            char spec_buf[32] = {0};
            if (spec_len >= sizeof(spec_buf)) {
                LOG_ERROR("Format specifier too long");
                return NULL;
            }

            if (arg_index >= argc) {
                LOG_ERROR("More placeholders than arguments");
                return NULL;
            }

            MemCopy(spec_buf, start, spec_len);
            spec_buf[spec_len] = '\0';

            // Validate format specifier
            FmtInfo fmt_info;
            if (!ParseFormatSpec(spec_buf, spec_len, &fmt_info)) {
                return NULL; // Error already logged by ParseFormatSpec
            }

            // Skip whitespace before value
            while (*in && IS_SPACE(*in))
                in++;

            // Use the type-specific reader
            TypeSpecificIO* io = &argv[arg_index++];
            if (!io->reader) {
                LOG_ERROR("Missing reader function");
                return NULL;
            }

            const char* next = io->reader(in, io->data);

            // Check if reading failed
            if (!next || next == in) {
                LOG_ERROR("Failed to read value for placeholder %zu", arg_index - 1);
                return NULL;
            }

            // Update input pointer
            in = next;

            // Skip whitespace after value
            while (*in && IS_SPACE(*in))
                in++;

            // Skip closing '}'
            p++;
            remaining--;
        } else {
            // Skip whitespace in format string if it's not part of a literal
            if (IS_SPACE(*p)) {
                // Skip whitespace in both format string and input
                while (remaining > 0 && IS_SPACE(*p)) {
                    p++;
                    remaining--;
                }
                while (*in && IS_SPACE(*in))
                    in++;
                continue;
            }

            // Match exact character from format string
            if (!in || *in != *p) {
                LOG_ERROR(
                    "Input '%.*s' does not match format string '%.*s'",
                    MIN2(remaining, 8),
                    in ? in : "(null)",
                    MIN2(remaining, 8),
                    p
                );
                return NULL;
            }
            in++;
            p++;
            remaining--;
        }
    }

    // Skip any trailing whitespace in input
    while (*in && IS_SPACE(*in))
        in++;

    // Check for extra input
    if (*in) {
        LOG_ERROR("Extra input after format string: '%.*s'", MIN2(8, ZstrLen(in)), in);
        return NULL;
    }

    return in;
}

#if defined(_WIN32)
#    include <io.h>
#    define ISATTY _isatty
#    define FILENO _fileno
#else
#    include <unistd.h>
#    define ISATTY isatty
#    define FILENO fileno
#endif

void FReadFmtInternal(FILE* file, const char* fmtstr, TypeSpecificIO* argv, size argc) {
    if (!file || !fmtstr) {
        LOG_FATAL("Invalid arguments");
    }

    Str buffer = StrInit();

    int    c;
    fpos_t start_pos;
    bool   can_rollback = false;

    // Try to check if the file is seekable
    int fd = FILENO(file);
    if (fd >= 0 && !ISATTY(fd)) {
        if (fgetpos(file, &start_pos) == 0) {
            can_rollback = true;
        } else {
            Str err = StrInit();
            LOG_ERROR("Could not save file position for rollback: %s", SysStrError(errno, &err)->data);
            StrDeinit(&err);
        }
    }

    while ((c = fgetc(file)) != EOF && c != '\n') {
        StrPushBack(&buffer, c);
    }

    if (buffer.length) {
        if (!StrReadFmtInternal(buffer.data, fmtstr, argv, argc)) {
            if (can_rollback) {
                fsetpos(file, &start_pos);
            } else {
                LOG_ERROR("Parse failed, and rollback not possible on non-seekable input");
            }
        }
    }

    StrDeinit(&buffer);
}

void _write_Str(Str* o, FmtInfo* fmt_info, Str* s) {
    if (!o || !fmt_info) {
        LOG_FATAL("Invalid arguments");
        return;
    }

    // Store original length to calculate content size later
    size start_len = o->length;

    // Handle null string
    if (!s) {
        StrPushBackZstr(o, "(null)");
    }
    // Handle null data pointer
    else if (!s->data) {
        StrPushBackZstr(o, "(null)");
    }
    // Handle empty string - don't need special handling, just apply padding if needed
    else if (s->length == 0) {
        // Empty string - no action needed, padding will be applied below
    } else {
        if (fmt_info->is_hex) {
            // Format each character as hex
            for (size i = 0; i < s->length; i++) {
                if (i > 0) {
                    StrPushBack(o, ' ');
                }
                // Create hex string for each character
                Str hex = StrInit();
                StrFromU64(&hex, (u8)s->data[i], 16, fmt_info->is_caps);
                // Ensure 2 digits with leading zero
                if (hex.length == 1) {
                    StrPushFront(&hex, '0');
                }
                StrPushBackZstr(o, "0x");
                StrMerge(o, &hex);
                StrDeinit(&hex);
            }
        } else {
            // If precision is specified, use it as max length
            size len = s->length;
            if (fmt_info->has_precision) {
                // Precision 0 means empty string (not an error)
                if (fmt_info->precision == 0) {
                    len = 0;
                } else {
                    len = MIN2(len, fmt_info->precision);
                }
            }

            // Copy string content
            for (size i = 0; i < len; i++) {
                StrPushBack(o, s->data[i]);
            }
        }
    }

    // Apply padding if width is specified
    if (fmt_info->width > 0) {
        size content_len = o->length - start_len;
        PadString(o, fmt_info->width, fmt_info->align, content_len);
    }
}

void _write_Zstr(Str* o, FmtInfo* fmt_info, const char** s) {
    if (!o || !fmt_info) {
        LOG_FATAL("Invalid arguments");
        return;
    }

    // Store original length to calculate content size later
    size start_len = o->length;

    // Handle null or empty string
    if (!s || !*s) {
        StrPushBackZstr(o, "(null)");
    } else if ((*s)[0] == '\0') {
        // Empty string - don't need special handling, just apply padding if needed
    } else {
        if (fmt_info->is_hex) {
            // Format each character as hex
            const char* str = *s;
            size        i   = 0;
            while (str[i]) {
                if (i > 0) {
                    StrPushBack(o, ' ');
                }
                // Create hex string for each character
                Str hex = StrInit();
                StrFromU64(&hex, (u8)str[i], 16, fmt_info->is_caps);
                // Ensure 2 digits with leading zero
                if (hex.length == 1) {
                    StrPushFront(&hex, '0');
                }
                StrPushBackZstr(o, "0x");
                StrMerge(o, &hex);
                StrDeinit(&hex);
                i++;
            }
        } else {
            // Get string length
            size        len = 0;
            const char* str = *s;
            while (str[len])
                len++;

            // If precision is specified, use it as max length
            if (fmt_info->has_precision) {
                // Precision 0 means empty string (not an error)
                if (fmt_info->precision == 0) {
                    len = 0;
                } else {
                    len = MIN2(len, fmt_info->precision);
                }
            }

            // Copy string content
            for (size i = 0; i < len; i++) {
                StrPushBack(o, str[i]);
            }
        }
    }

    // Apply padding if width is specified
    if (fmt_info->width > 0) {
        size content_len = o->length - start_len;
        PadString(o, fmt_info->width, fmt_info->align, content_len);
    }
}

void _write_u64(Str* o, FmtInfo* fmt_info, u64* v) {
    if (!o || !fmt_info || !v) {
        LOG_FATAL("Invalid arguments");
        return;
    }

    // Store original length to calculate content size later
    size start_len = o->length;

    // Create temporary buffer for number formatting
    Str temp = StrInit();

    // Determine base based on format flags
    u8 base = 10; // default is decimal
    if (fmt_info->is_hex) {
        base = 16;
    } else if (fmt_info->is_binary) {
        base = 2;
    } else if (fmt_info->is_octal) {
        base = 8;
    }

    // Use StrFromU64 directly with the appropriate base
    StrFromU64(&temp, *v, base, fmt_info->is_caps);

    // Merge the formatted number into output
    StrMerge(o, &temp);
    StrDeinit(&temp);

    // Apply padding if width is specified
    if (fmt_info->width > 0) {
        size content_len = o->length - start_len;
        PadString(o, fmt_info->width, fmt_info->align, content_len);
    }
}

void _write_u32(Str* o, FmtInfo* fmt_info, u32* v) {
    u64 val = *v;
    _write_u64(o, fmt_info, &val);
}

void _write_u16(Str* o, FmtInfo* fmt_info, u16* v) {
    u64 val = *v;
    _write_u64(o, fmt_info, &val);
}

void _write_u8(Str* o, FmtInfo* fmt_info, u8* v) {
    if (!o || !fmt_info || !v) {
        LOG_FATAL("Invalid arguments");
        return;
    }

    // Store original length to calculate content size later
    size start_len = o->length;

    // Create temporary buffer for number formatting
    Str temp = StrInit();

    // Determine base based on format flags
    u8 base = 10; // default is decimal
    if (fmt_info->is_hex) {
        base = 16;
    } else if (fmt_info->is_binary) {
        base = 2;
    } else if (fmt_info->is_octal) {
        base = 8;
    }

    // Use StrFromU64 directly with the appropriate base
    StrFromU64(&temp, *v, base, fmt_info->is_caps);

    // Merge the formatted number into output
    StrMerge(o, &temp);
    StrDeinit(&temp);

    // Apply padding if width is specified
    if (fmt_info->width > 0) {
        size content_len = o->length - start_len;
        PadString(o, fmt_info->width, fmt_info->align, content_len);
    }
}

void _write_i64(Str* o, FmtInfo* fmt_info, i64* v) {
    if (!o || !fmt_info || !v) {
        LOG_FATAL("Invalid arguments");
        return;
    }

    // Store original length to calculate content size later
    size start_len = o->length;

    // Create temporary buffer for number formatting
    Str temp = StrInit();

    // Determine base based on format flags
    u8 base = 10; // default is decimal
    if (fmt_info->is_hex) {
        base = 16;
    } else if (fmt_info->is_binary) {
        base = 2;
    } else if (fmt_info->is_octal) {
        base = 8;
    }

    // Use StrFromI64 directly with the appropriate base
    StrFromI64(&temp, *v, base, fmt_info->is_caps);

    // Merge the formatted number into output
    StrMerge(o, &temp);
    StrDeinit(&temp);

    // Apply padding if width is specified
    if (fmt_info->width > 0) {
        size content_len = o->length - start_len;
        PadString(o, fmt_info->width, fmt_info->align, content_len);
    }
}

void _write_i32(Str* o, FmtInfo* fmt_info, i32* v) {
    i64 val = *v;
    _write_i64(o, fmt_info, &val);
}

void _write_i16(Str* o, FmtInfo* fmt_info, i16* v) {
    if (!o || !fmt_info || !v) {
        LOG_FATAL("Invalid arguments");
        return;
    }

    // Store original length to calculate content size later
    size start_len = o->length;

    // Create temporary buffer for number formatting
    Str temp = StrInit();

    // Use StrFromI64 directly with the appropriate base
    StrFromI64(&temp, *v, 10, fmt_info->is_caps);

    // Merge the formatted number into output
    StrMerge(o, &temp);
    StrDeinit(&temp);

    // Apply padding if width is specified
    if (fmt_info->width > 0) {
        size content_len = o->length - start_len;
        PadString(o, fmt_info->width, fmt_info->align, content_len);
    }
}

void _write_i8(Str* o, FmtInfo* fmt_info, i8* v) {
    if (!o || !fmt_info || !v) {
        LOG_FATAL("Invalid arguments");
        return;
    }

    // Store original length to calculate content size later
    size start_len = o->length;

    // Create temporary buffer for number formatting
    Str temp = StrInit();

    // Use StrFromI64 directly with the appropriate base
    StrFromI64(&temp, *v, 10, fmt_info->is_caps);

    // Merge the formatted number into output
    StrMerge(o, &temp);
    StrDeinit(&temp);

    // Apply padding if width is specified
    if (fmt_info->width > 0) {
        size content_len = o->length - start_len;
        PadString(o, fmt_info->width, fmt_info->align, content_len);
    }
}

void _write_f64(Str* o, FmtInfo* fmt_info, f64* v) {
    if (!o || !fmt_info || !v) {
        LOG_FATAL("Invalid arguments");
        return;
    }

    // Store original length to calculate content size later
    size start_len = o->length;

    // Handle special cases directly here to avoid StrFromF64 issues
    if (isnan(*v)) {
        // Direct string append for NaN
        if (fmt_info->is_caps) {
            StrPushBackZstr(o, "NAN");
        } else {
            StrPushBackZstr(o, "nan");
        }
    } else if (isinf(*v)) {
        // Direct string append for infinity
        if (*v < 0) {
            StrPushBack(o, '-');
        }

        if (fmt_info->is_caps) {
            StrPushBackZstr(o, "INF");
        } else {
            StrPushBackZstr(o, "inf");
        }
    } else {
        // Normal case - use StrFromF64
        // Create temporary buffer for number formatting
        Str temp = StrInit();

        // Use StrFromF64 directly with the appropriate parameters
        u8 precision = fmt_info->has_precision ? fmt_info->precision : 6;
        StrFromF64(&temp, *v, precision, fmt_info->is_scientific, fmt_info->is_caps);

        // Merge the formatted number into output
        StrMerge(o, &temp);
        StrDeinit(&temp);
    }

    // Apply padding if width is specified
    if (fmt_info->width > 0) {
        size content_len = o->length - start_len;
        PadString(o, fmt_info->width, fmt_info->align, content_len);
    }
}

void _write_f32(Str* o, FmtInfo* fmt_info, f32* v) {
    f64 val = *v;
    _write_f64(o, fmt_info, &val);
}

// Helper function to handle escape sequences
static char ProcessEscape(const char** str) {
    if (!str || !*str)
        return 0;

    const char* s = *str;
    if (*s != '\\') {
        LOG_ERROR("ProcessEscape called on non-escape sequence");
        return 0;
    }

    s++; // Skip backslash
    char result = 0;

    switch (*s) {
        case 'n' :
            result = '\n';
            break;
        case 'r' :
            result = '\r';
            break;
        case 't' :
            result = '\t';
            break;
        case 'b' :
            result = '\b';
            break;
        case 'f' :
            result = '\f';
            break;
        case 'v' :
            result = '\v';
            break;
        case 'a' :
            result = '\a';
            break;
        case '\\' :
            result = '\\';
            break;
        case '"' :
            result = '"';
            break;
        case '\'' :
            result = '\'';
            break;
        case '0' :
            result = '\0';
            break;
        case 'x' : { // Hex escape
            s++;
            if (!isxdigit(s[0]) || !isxdigit(s[1])) {
                LOG_ERROR("Invalid hex escape sequence");
                return 0;
            }
            char hex[3] = {s[0], s[1], '\0'};
            result      = (char)strtol(hex, NULL, 16);
            s++; // Point to second hex digit
            break;
        }
        default :
            LOG_ERROR("Invalid escape sequence '\\%c'", *s);
            return 0;
    }

    *str = s; // Update pointer to last processed character
    return result;
}

const char* _read_Str(const char* i, Str* s) {
    if (!i || !s)
        LOG_FATAL("Invalid arguments");

    // Skip leading whitespace
    while (IS_SPACE(*i))
        i++;

    // Check for empty input
    if (!*i) {
        LOG_ERROR("Empty input string");
        return i;
    }

    // Initialize output string
    *s = StrInit();

    // Check for quoted string
    char quote = 0;
    if (*i == '"' || *i == '\'') {
        quote = *i++;
    }

    while (*i) {
        if (quote) {
            // Quoted string mode
            if (*i == '\\') {
                const char* curr = i;
                char        c    = ProcessEscape(&curr);
                if (c == 0) { // Error in escape sequence
                    StrDeinit(s);
                    return NULL;
                }
                i = curr + 1; // Move past the escape sequence
                StrPushBack(s, c);
            } else if (*i == quote) {
                i++;          // Skip closing quote
                return i;     // Successfully read quoted string
            } else {
                StrPushBack(s, *i++);
            }
        } else {
            // Unquoted string mode - read until whitespace
            if (IS_SPACE(*i)) {
                return i; // Successfully read unquoted string
            }

            if (*i == '\\') {
                const char* curr = i;
                char        c    = ProcessEscape(&curr);
                if (c == 0) { // Error in escape sequence
                    StrDeinit(s);
                    return NULL;
                }
                i = curr + 1; // Move past the escape sequence
                StrPushBack(s, c);
            } else {
                StrPushBack(s, *i++);
            }
        }
    }

    // If we get here with a quote, the string was unterminated
    if (quote) {
        LOG_ERROR("Unterminated quoted string");
        StrDeinit(s);
        return NULL;
    }

    // Successfully read unquoted string that ended at EOF
    return i;
}

// Helper function to check if a character is valid for number parsing
static bool IsValidNumberChar(char c, bool is_first_char, bool allow_decimal) {
    // Allow digits
    if (IS_DIGIT(c))
        return true;

    // Allow signs only at the beginning
    if ((c == '+' || c == '-') && is_first_char)
        return true;

    // Allow decimal point if allowed
    if (c == '.' && allow_decimal)
        return true;

    // Allow base prefixes (only at the beginning or after a sign)
    if (c == '0' && (is_first_char || (is_first_char + 1)))
        return true;

    // Allow 'x', 'b', 'o' for hex/binary/octal after '0'
    // Note: We only get here for the second character in "0x", "0b", "0o"
    if (!is_first_char && (c == 'x' || c == 'X' || c == 'b' || c == 'B' || c == 'o' || c == 'O')) {
        // Check if the previous character was '0'
        // This will be validated by the base 0 parsing logic later
        return true;
    }

    // Allow hex letters only for hexadecimal base (after 0x)
    // This is handled by the base detection in the parsing functions
    // We will just collect characters here and let the parser reject invalid ones
    if ((c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')) {
        return true;
    }

    // Allow 'e' or 'E' for scientific notation if decimal is allowed
    if (allow_decimal && (c == 'e' || c == 'E'))
        return true;

    return false;
}

// Create a helper function to check if the parsed string contains only valid numeric characters
static bool IsValidNumericString(const Str* str, bool allow_float) {
    if (!str || !str->data)
        return false;

    // Empty string is invalid
    if (str->length == 0)
        return false;

    // Special floating point values: inf, nan
    if (allow_float) {
        if (str->length == 3) {
            if ((str->data[0] == 'i' || str->data[0] == 'I') && (str->data[1] == 'n' || str->data[1] == 'N') &&
                (str->data[2] == 'f' || str->data[2] == 'F')) {
                return true; // "inf"
            }
            if ((str->data[0] == 'n' || str->data[0] == 'N') && (str->data[1] == 'a' || str->data[1] == 'A') &&
                (str->data[2] == 'n' || str->data[2] == 'N')) {
                return true; // "nan"
            }
        }

        if (str->length == 4 && str->data[0] == '-') {
            if ((str->data[1] == 'i' || str->data[1] == 'I') && (str->data[2] == 'n' || str->data[2] == 'N') &&
                (str->data[3] == 'f' || str->data[3] == 'F')) {
                return true; // "-inf"
            }
        }
    }

    // Check for decimal, octal, hex, or binary prefix
    bool is_hex = false;
    bool is_bin = false;
    bool is_oct = false;

    if (str->length > 2 && str->data[0] == '0') {
        if (str->data[1] == 'x' || str->data[1] == 'X') {
            is_hex = true;
        } else if (str->data[1] == 'b' || str->data[1] == 'B') {
            is_bin = true;
        } else if (str->data[1] == 'o' || str->data[1] == 'O') {
            is_oct = true;
        }
    }

    // For floating point, we need to track decimal point and scientific notation
    bool has_decimal = false;
    bool has_exp     = false;

    // Check each character
    for (size i = 0; i < str->length; i++) {
        char c = str->data[i];

        // Skip prefix
        if ((is_hex || is_bin || is_oct) && (i == 0 || i == 1)) {
            continue;
        }

        // Check sign (only valid at start or after 'e'/'E')
        if ((c == '+' || c == '-') &&
            (i == 0 || (allow_float && has_exp && (i > 0 && (str->data[i - 1] == 'e' || str->data[i - 1] == 'E'))))) {
            continue;
        }

        // Check decimal point (only for float and only once)
        if (allow_float && c == '.') {
            if (has_decimal) {
                return false; // Second decimal point
            }
            has_decimal = true;
            continue;
        }

        // Check scientific notation (only for float and only once)
        if (allow_float && (c == 'e' || c == 'E')) {
            if (has_exp) {
                return false; // Second exponent
            }
            has_exp = true;
            continue;
        }

        // Check digits
        if (c >= '0' && c <= '9') {
            continue;
        }

        // Check hex digits
        if (is_hex && ((c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F'))) {
            continue;
        }

        // Check binary digits
        if (is_bin && (c == '0' || c == '1')) {
            continue;
        }

        // Check octal digits
        if (is_oct && (c >= '0' && c <= '7')) {
            continue;
        }

        // Any other character is invalid
        return false;
    }

    // Validate special requirements for float
    if (allow_float) {
        // If we have an exponent, make sure it's not at the end
        if (has_exp) {
            char last_char = str->data[str->length - 1];
            if (last_char == 'e' || last_char == 'E' || last_char == '+' || last_char == '-') {
                return false; // Incomplete exponent
            }
        }
    }

    return true;
}

const char* _read_f64(const char* i, f64* v) {
    if (!i || !v)
        LOG_FATAL("Invalid arguments");

    // Skip whitespace
    while (IS_SPACE(*i))
        i++;

    // Check for empty string
    if (!*i) {
        LOG_ERROR("Failed to parse f64: empty input");
        return i;
    }

    // Check for special values (inf, nan)
    if ((*i == 'i' || *i == 'I' || *i == 'n' || *i == 'N') || (*i == '-' && (*(i + 1) == 'i' || *(i + 1) == 'I'))) {
        // For special values, use the original approach
        const char* start = i;
        while (*i && !IS_SPACE(*i))
            i++;

        // Create a temporary Str for parsing
        Str temp = StrInitFromCstr(start, i - start);

        // Try to parse as special value
        if (StrToF64(&temp, v)) {
            StrDeinit(&temp);
            return i;
        }
        StrDeinit(&temp);

        // If parsing failed, fall back to the new approach
        i = start;
    }

    // Find the end of the number using more precise rules
    const char* start       = i;
    size        pos         = 0;
    bool        has_decimal = false; // Track if we've seen a decimal point

    // Parse character by character
    while (i[pos]) {
        // Only allow one decimal point
        if (i[pos] == '.') {
            if (has_decimal)
                break; // Second decimal point - stop
            has_decimal = true;
        }

        // If we see an 'e' or 'E', check if it's followed by a valid exponent
        if ((i[pos] == 'e' || i[pos] == 'E') && pos > 0) {
            // Move to the next character after 'e'
            pos++;

            // Allow sign in exponent
            if (i[pos] == '+' || i[pos] == '-')
                pos++;

            // Must have at least one digit in exponent
            if (!IS_DIGIT(i[pos])) {
                // Invalid exponent - back up to before the 'e'
                pos--;
                break;
            }

            // Continue with exponent digits
            while (IS_DIGIT(i[pos]))
                pos++;
            break; // Stop after exponent
        }

        // Check if character is valid for a number
        if (!IsValidNumberChar(i[pos], pos == 0, true)) {
            break;
        }

        pos++;
    }

    // Create a temporary Str for parsing
    Str temp = StrInitFromCstr(start, pos);

    // Validate the string is a proper floating point number
    if (!IsValidNumericString(&temp, true)) {
        LOG_ERROR("Invalid floating point format");
        StrDeinit(&temp);
        return start;
    }

    // Use StrToF64 directly
    if (!StrToF64(&temp, v)) {
        LOG_ERROR("Failed to parse f64");
        StrDeinit(&temp);
        return start;
    }

    StrDeinit(&temp);
    return start + pos;
}

const char* _read_u8(const char* i, u8* v) {
    if (!i || !v)
        LOG_FATAL("Invalid arguments");

    // Skip whitespace
    while (IS_SPACE(*i))
        i++;

    // Check for empty string
    if (!*i) {
        LOG_ERROR("Failed to parse u8: empty input");
        return i;
    }

    // Find the end of the number using more precise rules
    const char* start = i;
    size        pos   = 0;

    // Parse character by character
    while (i[pos]) {
        // Check if character is valid for a number
        if (!IsValidNumberChar(i[pos], pos == 0, false)) {
            break;
        }

        pos++;
    }

    // Create a temporary Str for parsing
    Str temp = StrInitFromCstr(start, pos);

    // Check for special prefixes with no digits
    if (temp.length == 2 && temp.data[0] == '0' &&
        (temp.data[1] == 'x' || temp.data[1] == 'X' || temp.data[1] == 'b' || temp.data[1] == 'B' ||
         temp.data[1] == 'o' || temp.data[1] == 'O')) {
        LOG_ERROR("Incomplete number format");
        StrDeinit(&temp);
        return start;
    }

    // Validate the string is a proper number
    if (!IsValidNumericString(&temp, false)) {
        LOG_ERROR("Invalid numeric format");
        StrDeinit(&temp);
        return start;
    }

    // Use base 0 to let strtoul detect the base from prefix
    u64 val;
    if (!StrToU64(&temp, &val, 0)) {
        LOG_ERROR("Failed to parse u8");
        StrDeinit(&temp);
        return start;
    }

    // Check for overflow
    if (val > UINT8_MAX) {
        LOG_ERROR("Value %llu exceeds u8 maximum (%u)", val, UINT8_MAX);
        StrDeinit(&temp);
        return start;
    }

    *v = (u8)val;
    StrDeinit(&temp);
    return start + pos;
}

const char* _read_u16(const char* i, u16* v) {
    if (!i || !v)
        LOG_FATAL("Invalid arguments");

    // Skip whitespace
    while (IS_SPACE(*i))
        i++;

    // Check for empty string
    if (!*i) {
        LOG_ERROR("Failed to parse u16: empty input");
        return i;
    }

    // Find the end of the number using more precise rules
    const char* start = i;
    size        pos   = 0;

    // Parse character by character
    while (i[pos]) {
        // Check if character is valid for a number
        if (!IsValidNumberChar(i[pos], pos == 0, false)) {
            break;
        }

        pos++;
    }

    // Create a temporary Str for parsing
    Str temp = StrInitFromCstr(start, pos);

    // Check for special prefixes with no digits
    if (temp.length == 2 && temp.data[0] == '0' &&
        (temp.data[1] == 'x' || temp.data[1] == 'X' || temp.data[1] == 'b' || temp.data[1] == 'B' ||
         temp.data[1] == 'o' || temp.data[1] == 'O')) {
        LOG_ERROR("Incomplete number format");
        StrDeinit(&temp);
        return start;
    }

    // Validate the string is a proper number
    if (!IsValidNumericString(&temp, false)) {
        LOG_ERROR("Invalid numeric format");
        StrDeinit(&temp);
        return start;
    }

    // Use base 0 to let strtoul detect the base from prefix
    u64 val;
    if (!StrToU64(&temp, &val, 0)) {
        LOG_ERROR("Failed to parse u16");
        StrDeinit(&temp);
        return start;
    }

    // Check for overflow
    if (val > UINT16_MAX) {
        LOG_ERROR("Value %llu exceeds u16 maximum (%u)", val, UINT16_MAX);
        StrDeinit(&temp);
        return start;
    }

    *v = (u16)val;
    StrDeinit(&temp);
    return start + pos;
}

const char* _read_u32(const char* i, u32* v) {
    if (!i || !v)
        LOG_FATAL("Invalid arguments");

    // Skip whitespace
    while (IS_SPACE(*i))
        i++;

    // Check for empty string
    if (!*i) {
        LOG_ERROR("Failed to parse u32: empty input");
        return i;
    }

    // Find the end of the number using more precise rules
    const char* start = i;
    size        pos   = 0;

    // Parse character by character
    while (i[pos]) {
        // Check if character is valid for a number
        if (!IsValidNumberChar(i[pos], pos == 0, false)) {
            break;
        }

        pos++;
    }

    // Create a temporary Str for parsing
    Str temp = StrInitFromCstr(start, pos);

    // Check for special prefixes with no digits
    if (temp.length == 2 && temp.data[0] == '0' &&
        (temp.data[1] == 'x' || temp.data[1] == 'X' || temp.data[1] == 'b' || temp.data[1] == 'B' ||
         temp.data[1] == 'o' || temp.data[1] == 'O')) {
        LOG_ERROR("Incomplete number format");
        StrDeinit(&temp);
        return start;
    }

    // Validate the string is a proper number
    if (!IsValidNumericString(&temp, false)) {
        LOG_ERROR("Invalid numeric format");
        StrDeinit(&temp);
        return start;
    }

    // Use base 0 to let strtoul detect the base from prefix
    u64 val;
    if (!StrToU64(&temp, &val, 0)) {
        LOG_ERROR("Failed to parse u32");
        StrDeinit(&temp);
        return start;
    }

    // Check for overflow
    if (val > UINT32_MAX) {
        LOG_ERROR("Value %llu exceeds u32 maximum (%u)", val, UINT32_MAX);
        StrDeinit(&temp);
        return start;
    }

    *v = (u32)val;
    StrDeinit(&temp);
    return start + pos;
}

const char* _read_u64(const char* i, u64* v) {
    if (!i || !v)
        LOG_FATAL("Invalid arguments");

    // Skip whitespace
    while (IS_SPACE(*i))
        i++;

    // Check for empty string
    if (!*i) {
        LOG_ERROR("Failed to parse u64: empty input");
        return i;
    }

    // Find the end of the number using more precise rules
    const char* start = i;
    size        pos   = 0;

    // Parse character by character
    while (i[pos]) {
        // Check if character is valid for a number
        if (!IsValidNumberChar(i[pos], pos == 0, false)) {
            break;
        }

        pos++;
    }

    // Create a temporary Str for parsing
    Str temp = StrInitFromCstr(start, pos);

    // Check for special prefixes with no digits
    if (temp.length == 2 && temp.data[0] == '0' &&
        (temp.data[1] == 'x' || temp.data[1] == 'X' || temp.data[1] == 'b' || temp.data[1] == 'B' ||
         temp.data[1] == 'o' || temp.data[1] == 'O')) {
        LOG_ERROR("Incomplete number format");
        StrDeinit(&temp);
        return start;
    }

    // Validate the string is a proper number
    if (!IsValidNumericString(&temp, false)) {
        LOG_ERROR("Invalid numeric format");
        StrDeinit(&temp);
        return start;
    }

    // Use base 0 to let strtoul detect the base from prefix
    if (!StrToU64(&temp, v, 0)) {
        LOG_ERROR("Failed to parse u64");
        StrDeinit(&temp);
        return start;
    }

    StrDeinit(&temp);
    return start + pos;
}

const char* _read_i8(const char* i, i8* v) {
    if (!i || !v)
        LOG_FATAL("Invalid arguments");

    // Skip whitespace
    while (IS_SPACE(*i))
        i++;

    // Check for empty string
    if (!*i) {
        LOG_ERROR("Failed to parse i8: empty input");
        return i;
    }

    // Find the end of the number using more precise rules
    const char* start = i;
    size        pos   = 0;

    // Parse character by character
    while (i[pos]) {
        // Check if character is valid for a number
        if (!IsValidNumberChar(i[pos], pos == 0, false)) {
            break;
        }

        pos++;
    }

    // Create a temporary Str for parsing
    Str temp = StrInitFromCstr(start, pos);

    // Check for special prefixes with no digits
    if (temp.length == 2 && temp.data[0] == '0' &&
        (temp.data[1] == 'x' || temp.data[1] == 'X' || temp.data[1] == 'b' || temp.data[1] == 'B' ||
         temp.data[1] == 'o' || temp.data[1] == 'O')) {
        LOG_ERROR("Incomplete number format");
        StrDeinit(&temp);
        return start;
    }

    // Validate the string is a proper number
    if (!IsValidNumericString(&temp, false)) {
        LOG_ERROR("Invalid numeric format");
        StrDeinit(&temp);
        return start;
    }

    // Use base 0 to let strtoul detect the base from prefix
    i64 val;
    if (!StrToI64(&temp, &val, 0)) {
        LOG_ERROR("Failed to parse i8");
        StrDeinit(&temp);
        return start;
    }

    // Check for overflow/underflow
    if (val > INT8_MAX || val < INT8_MIN) {
        LOG_ERROR("Value %lld outside i8 range (%d to %d)", val, INT8_MIN, INT8_MAX);
        StrDeinit(&temp);
        return start;
    }

    *v = (i8)val;
    StrDeinit(&temp);
    return start + pos;
}

const char* _read_i16(const char* i, i16* v) {
    if (!i || !v)
        LOG_FATAL("Invalid arguments");

    // Skip whitespace
    while (IS_SPACE(*i))
        i++;

    // Check for empty string
    if (!*i) {
        LOG_ERROR("Failed to parse i16: empty input");
        return i;
    }

    // Find the end of the number using more precise rules
    const char* start = i;
    size        pos   = 0;

    // Parse character by character
    while (i[pos]) {
        // Check if character is valid for a number
        if (!IsValidNumberChar(i[pos], pos == 0, false)) {
            break;
        }

        pos++;
    }

    // Create a temporary Str for parsing
    Str temp = StrInitFromCstr(start, pos);

    // Check for special prefixes with no digits
    if (temp.length == 2 && temp.data[0] == '0' &&
        (temp.data[1] == 'x' || temp.data[1] == 'X' || temp.data[1] == 'b' || temp.data[1] == 'B' ||
         temp.data[1] == 'o' || temp.data[1] == 'O')) {
        LOG_ERROR("Incomplete number format");
        StrDeinit(&temp);
        return start;
    }

    // Validate the string is a proper number
    if (!IsValidNumericString(&temp, false)) {
        LOG_ERROR("Invalid numeric format");
        StrDeinit(&temp);
        return start;
    }

    // Use base 0 to let strtoul detect the base from prefix
    i64 val;
    if (!StrToI64(&temp, &val, 0)) {
        LOG_ERROR("Failed to parse i16");
        StrDeinit(&temp);
        return start;
    }

    // Check for overflow/underflow
    if (val > INT16_MAX || val < INT16_MIN) {
        LOG_ERROR("Value %lld outside i16 range (%d to %d)", val, INT16_MIN, INT16_MAX);
        StrDeinit(&temp);
        return start;
    }

    *v = (i16)val;
    StrDeinit(&temp);
    return start + pos;
}

const char* _read_i32(const char* i, i32* v) {
    if (!i || !v)
        LOG_FATAL("Invalid arguments");

    // Skip whitespace
    while (IS_SPACE(*i))
        i++;

    // Check for empty string
    if (!*i) {
        LOG_ERROR("Failed to parse i32: empty input");
        return i;
    }

    // Find the end of the number using more precise rules
    const char* start = i;
    size        pos   = 0;

    // Parse character by character
    while (i[pos]) {
        // Check if character is valid for a number
        if (!IsValidNumberChar(i[pos], pos == 0, false)) {
            break;
        }

        pos++;
    }

    // Create a temporary Str for parsing
    Str temp = StrInitFromCstr(start, pos);

    // Check for special prefixes with no digits
    if (temp.length == 2 && temp.data[0] == '0' &&
        (temp.data[1] == 'x' || temp.data[1] == 'X' || temp.data[1] == 'b' || temp.data[1] == 'B' ||
         temp.data[1] == 'o' || temp.data[1] == 'O')) {
        LOG_ERROR("Incomplete number format");
        StrDeinit(&temp);
        return start;
    }

    // Validate the string is a proper number
    if (!IsValidNumericString(&temp, false)) {
        LOG_ERROR("Invalid numeric format");
        StrDeinit(&temp);
        return start;
    }

    // Use base 0 to let strtoul detect the base from prefix
    i64 val;
    if (!StrToI64(&temp, &val, 0)) {
        LOG_ERROR("Failed to parse i32");
        StrDeinit(&temp);
        return start;
    }

    // Check for overflow/underflow
    if (val > INT32_MAX || val < INT32_MIN) {
        LOG_ERROR("Value %lld outside i32 range (%d to %d)", val, INT32_MIN, INT32_MAX);
        StrDeinit(&temp);
        return start;
    }

    *v = (i32)val;
    StrDeinit(&temp);
    return start + pos;
}

const char* _read_i64(const char* i, i64* v) {
    if (!i || !v)
        LOG_FATAL("Invalid arguments");

    // Skip whitespace
    while (IS_SPACE(*i))
        i++;

    // Check for empty string
    if (!*i) {
        LOG_ERROR("Failed to parse i64: empty input");
        return i;
    }

    // Find the end of the number using more precise rules
    const char* start = i;
    size        pos   = 0;

    // Parse character by character
    while (i[pos]) {
        // Check if character is valid for a number
        if (!IsValidNumberChar(i[pos], pos == 0, false)) {
            break;
        }

        pos++;
    }

    // Create a temporary Str for parsing
    Str temp = StrInitFromCstr(start, pos);

    // Check for special prefixes with no digits
    if (temp.length == 2 && temp.data[0] == '0' &&
        (temp.data[1] == 'x' || temp.data[1] == 'X' || temp.data[1] == 'b' || temp.data[1] == 'B' ||
         temp.data[1] == 'o' || temp.data[1] == 'O')) {
        LOG_ERROR("Incomplete number format");
        StrDeinit(&temp);
        return start;
    }

    // Validate the string is a proper number
    if (!IsValidNumericString(&temp, false)) {
        LOG_ERROR("Invalid numeric format");
        StrDeinit(&temp);
        return start;
    }

    // Use base 0 to let strtoul detect the base from prefix
    if (!StrToI64(&temp, v, 0)) {
        LOG_ERROR("Failed to parse i64");
        StrDeinit(&temp);
        return start;
    }

    StrDeinit(&temp);
    return start + pos;
}

const char* _read_Zstr(const char* i, const char** out) {
    if (!i || !out)
        LOG_FATAL("Invalid arguments");

    // Use Str to read the string
    Str         temp = StrInit();
    const char* next = _read_Str(i, &temp);

    // Check if reading failed
    if (next == i) {
        StrDeinit(&temp);
        return i;
    }

    // Allocate and copy to null-terminated string
    char* result = malloc(temp.length + 1);
    if (!result) {
        LOG_ERROR("Failed to allocate memory for string");
        StrDeinit(&temp);
        return i;
    }

    MemCopy(result, temp.data, temp.length);
    result[temp.length] = '\0';

    *out = result;
    StrDeinit(&temp);
    return next;
}

void _write_UnsupportedType(Str* o, FmtInfo* fmt_info, const char** s) {
    (void)o;
    (void)fmt_info;
    (void)s;
    LOG_FATAL("Attempt to write unsupported type");
}

const char* _read_UnsupportedType(const char* i, const char** s) {
    (void)s;
    LOG_FATAL("Attempt to read unsupported type.");
    return i;
}

const char* _read_f32(const char* i, f32* v) {
    if (!i || !v)
        LOG_FATAL("Invalid arguments");

    // Skip whitespace
    while (IS_SPACE(*i))
        i++;

    // Check for empty string
    if (!*i) {
        LOG_ERROR("Failed to parse f32: empty input");
        return i;
    }

    // Check for special values (inf, nan)
    if ((*i == 'i' || *i == 'I' || *i == 'n' || *i == 'N') || (*i == '-' && (*(i + 1) == 'i' || *(i + 1) == 'I'))) {
        // For special values, use the original approach
        const char* start = i;
        while (*i && !IS_SPACE(*i))
            i++;

        // Create a temporary Str for parsing
        Str temp = StrInitFromCstr(start, i - start);

        // Try to parse as special value
        f64 val;
        if (StrToF64(&temp, &val)) {
            *v = (f32)val;
            StrDeinit(&temp);
            return i;
        }
        StrDeinit(&temp);

        // If parsing failed, fall back to the new approach
        i = start;
    }

    // Find the end of the number using more precise rules
    const char* start       = i;
    size        pos         = 0;
    bool        has_decimal = false; // Track if we've seen a decimal point

    // Parse character by character
    while (i[pos]) {
        // Only allow one decimal point
        if (i[pos] == '.') {
            if (has_decimal)
                break; // Second decimal point - stop
            has_decimal = true;
        }

        // If we see an 'e' or 'E', check if it's followed by a valid exponent
        if ((i[pos] == 'e' || i[pos] == 'E') && pos > 0) {
            // Move to the next character after 'e'
            pos++;

            // Allow sign in exponent
            if (i[pos] == '+' || i[pos] == '-')
                pos++;

            // Must have at least one digit in exponent
            if (!IS_DIGIT(i[pos])) {
                // Invalid exponent - back up to before the 'e'
                pos--;
                break;
            }

            // Continue with exponent digits
            while (IS_DIGIT(i[pos]))
                pos++;
            break; // Stop after exponent
        }

        // Check if character is valid for a number
        if (!IsValidNumberChar(i[pos], pos == 0, true)) {
            break;
        }

        pos++;
    }

    // Create a temporary Str for parsing
    Str temp = StrInitFromCstr(start, pos);

    // Validate the string is a proper floating point number
    if (!IsValidNumericString(&temp, true)) {
        LOG_ERROR("Invalid floating point format");
        StrDeinit(&temp);
        return start;
    }

    // Use StrToF64 directly
    f64 val;
    if (!StrToF64(&temp, &val)) {
        LOG_ERROR("Failed to parse f32");
        StrDeinit(&temp);
        return start;
    }

    *v = (f32)val;
    StrDeinit(&temp);
    return start + pos;
}

void _write_char(Str* o, FmtInfo* fmt_info, char* v) {
    if (!o || !fmt_info || !v) {
        LOG_FATAL("Invalid arguments");
    }

    u8 vx = (u8)*v;
    if (vx > 0x7f) {
        StrPushBackZstr(o, "\\x");
        fmt_info->is_hex = true;
        _write_u8(o, fmt_info, &vx);
    } else {
        StrPushBack(o, *v);
    }
}

const char* _read_char(const char* in, char* v){
    if(!in || !v) {
        LOG_FATAL("Invalid arguments");
    }

    if(in[0] == '\\' && in[1] == 'x') {
        u8 vx = 0;
        const char* out =_read_u8(in + 2,&vx );
        *v = vx;
        return out;
    } else {
        *v = *in;
        return in + 1;
    }
}
